### ISSUE TITLE
Design and implement GitHub rule checker for PR compliance validation

### ISSUE THREAD

**Issue by tyabonil** [tyabonil/cursor_rules#37]
# GitHub Rule Checker - Design and Implementation

## 🎯 Objective
Build an automated GitHub rule checker that validates each new PR against MANDATORY-RULES.md and provides compliance feedback through PR comments.

### **Level 1 Security Checks (BLOCKER)**
- [ ] Detect secrets in commits (.env files, API keys, passwords, tokens)
- [ ] Detect environment file overwrites without permission
- [ ] Block merge if Level 1 violations found

### **Level 2 Workflow Checks (MANDATORY)** 
- [ ] Verify issue reference in PR title/description
- [ ] Validate branch naming convention (feature/issue-{number}-{description})
- [ ] Check if PROJECT_CONTEXT.md updated for significant changes
- [ ] Verify test coverage reports included
- [ ] Detect if MCP GitHub API tools were used vs terminal git (challenging)

### **Level 3 Quality Checks (MANDATORY)**
- [ ] Validate 100% test coverage for new code
- [ ] Verify Copilot review was requested
- [ ] Check that all PR feedback has been addressed
- [ ] Ensure thought process documentation on related issues

### **Level 4 Pattern Checks (RECOMMENDED)**
- [ ] File size validation (≤300 lines)
- [ ] Code duplication detection
- [ ] Simple solution patterns

### Option 1: GitHub Actions Workflow
**Pros:**
- Native GitHub integration
- Runs on PR events (opened, synchronize, ready_for_review)
- Can access PR diff, files, comments via GitHub API
- Can post comments and update status checks
- Free for public repos

**Cons:**
- Limited by GitHub Actions runtime limits
- Requires workflow file in repository

### Option 2: GitHub App/Webhook
**Pros:**
- Real-time response to PR events
- More flexible than Actions
- Can run on external infrastructure
- Better for complex rule analysis

**Cons:**
- Requires hosting/infrastructure
- More complex setup and maintenance
- Authentication complexity

### Option 3: Hybrid Approach
**Pros:**
- GitHub Actions for simple checks
- External service for complex analysis
- Best of both worlds

**Cons:**
- More complex architecture
- Multiple components to maintain

### **Decision Points:**
1. How to detect MCP vs terminal git usage?
2. How to validate test coverage requirements?
3. How to check if Copilot review was requested?
4. What should trigger rule checker execution?
5. How to handle rule violations (comments, status checks, blocking)?

## 🎯 Success Criteria
- [ ] Automatically detects all Level 1-3 rule violations
- [ ] Posts clear, actionable feedback comments on PRs
- [ ] Blocks merging for critical violations
- [ ] Provides compliance checklist for manual verification
- [ ] Minimizes false positives
- [ ] Easy to maintain and update rules

## 📝 Implementation Phases
1. **Phase 1**: Design architecture and rule detection logic
2. **Phase 2**: Implement core rule validation engine
3. **Phase 3**: Build GitHub integration (comments, status checks)
4. **Phase 4**: Testing and refinement
5. **Phase 5**: Documentation and deployment

## 🚀 Priority
**P1-HIGH** - Important for ensuring rule compliance across all PRs

## 🔗 Related Issues
- Will create follow-up implementation issues based on agreed design

---

**Note**: This issue captures the design discussion and will be updated with decisions made during planning.

**Comment by tyabonil** [comment]
## 🏗️ **Hosting/Deployment Strategy Discussion**

### **Question from @tyabonil**: Where will this action be hosted/deployed? Example with private repo needed.

## 🎯 **Hosting Options Analysis**

### **Option 1: Self-Hosted in Each Repository (RECOMMENDED)**
Each repository includes the workflow file directly.

**Pros:**
- Repository-specific customization
- No external dependencies
- Full control over rule versions
- Works seamlessly with private repos

**Cons:**
- Workflow duplication across repos
- Updates require changes in each repo

### **Option 2: Centralized Reusable Action**
Create a dedicated rule-checker repository with reusable action.

**Pros:**
- Single source of truth for rule logic
- Easy updates across all repos
- Consistent rule enforcement

**Cons:**
- Private repo access complexity
- Dependency on external repo

### **Option 3: Composite Action + Self-Hosted**
Hybrid approach with shared logic but local workflows.

## 📋 **Private Repository Example**

### **Setup for Private Repository: `company/private-app`**

```yaml
# .github/workflows/mandatory-rules-check.yml
name: MANDATORY Rules Compliance

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  rule-compliance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      issues: read
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for diff analysis
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Download MANDATORY-RULES.md
        run: |
          # Download latest rules from cursor_rules repo
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.raw" \
               -o rules.md \
               "https://api.github.com/repos/tyabonil/cursor_rules/contents/MANDATORY-RULES.md"
               
      - name: Install rule checker dependencies
        run: |
          npm init -y
          npm install @actions/core @actions/github lodash
          
      - name: Run Rule Compliance Check
        id: rule-check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            
            // Import our rule checking logic
            const ruleChecker = require('./scripts/rule-checker.js');
            
            // Get PR information
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            // Get PR files and diff
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            // Run compliance checks
            const results = await ruleChecker.checkCompliance(pr, files, github, context);
            
            // Post compliance report
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: results.reportMarkdown
            });
            
            // Set status check
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: pr.head.sha,
              state: results.passing ? 'success' : 'failure',
              context: 'MANDATORY Rules Compliance',
              description: `${results.score}/10 compliance score`
            });
            
            return results;
```

### **Required Repository Structure**
```
company/private-app/
├── .github/
│   └── workflows/
│       └── mandatory-rules-check.yml
├── scripts/
│   └── rule-checker.js               # Core rule validation logic
├── .cursorrules                      # Local rules (override general)
└── PROJECT_CONTEXT.md               # Required by rules
```

### **Core Rule Checker Implementation**
```javascript
// scripts/rule-checker.js
module.exports = {
  async checkCompliance(pr, files, github, context) {
    const violations = [];
    let score = 10;
    
    // Level 1: Security Checks (BLOCKER)
    const securityViolations = await this.checkLevel1Security(files);
    violations.push(...securityViolations);
    
    // Level 2: Workflow Checks (MANDATORY)
    const workflowViolations = await this.checkLevel2Workflow(pr, files, github, context);
    violations.push(...workflowViolations);
    
    // Level 3: Quality Checks (MANDATORY)
    const qualityViolations = await this.checkLevel3Quality(pr, files, github, context);
    violations.push(...qualityViolations);
    
    // Calculate compliance score
    const criticalViolations = violations.filter(v => v.level <= 2);
    const blocking = criticalViolations.length > 0;
    score -= violations.length;
    
    return {
      violations,
      score: Math.max(0, score),
      passing: !blocking,
      reportMarkdown: this.generateReport(violations, score, blocking)
    };
  },
  
  async checkLevel1Security(files) {
    const violations = [];
    
    for (const file of files) {
      // Check for secrets in file content
      if (this.containsSecrets(file.patch)) {
        violations.push({
          level: 1,
          type: 'SECURITY',
          severity: 'BLOCKER',
          message: `Potential secrets detected in ${file.filename}`,
          file: file.filename
        });
      }
      
      // Check for .env file modifications
      if (file.filename.includes('.env') && file.status !== 'added') {
        violations.push({
          level: 1,
          type: 'SECURITY', 
          severity: 'BLOCKER',
          message: `Environment file modified: ${file.filename}`,
          file: file.filename
        });
      }
    }
    
    return violations;
  }
  
  // Additional methods for Level 2, 3, 4 checks...
};
```

## 💰 **Cost Considerations for Private Repos**

### **GitHub Actions Minutes Usage**
- **Free tier**: 2,000 minutes/month for private repos
- **Pro plan**: 3,000 minutes/month
- **Team plan**: 10,000 minutes/month
- **Enterprise**: 50,000 minutes/month

### **Estimated Usage per PR**
- **Rule checking workflow**: ~2-5 minutes per run
- **Typical PR lifecycle**: 3-5 runs (initial + updates)
- **Monthly estimate**: 50 PRs × 4 runs × 3 minutes = 600 minutes

### **Cost Optimization Strategies**
```yaml
# Only run on specific conditions
on:
  pull_request:
    types: [opened, ready_for_review]  # Skip synchronize for drafts
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
```

## 🔐 **Private Repository Security Configuration**

### **Required Secrets/Permissions**
```yaml
# Repository Settings → Secrets and Variables
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatic
RULES_ACCESS_TOKEN: ${{ secrets.RULES_ACCESS_TOKEN }}  # If accessing private cursor_rules

# Workflow Permissions
permissions:
  contents: read          # Read repository files
  pull-requests: write    # Comment on PRs
  checks: write          # Set status checks
  issues: read           # Read linked issues
```

### **Access Control**
- Rule checker only accesses PR data and changed files
- No access to sensitive environment variables
- Runs in isolated GitHub Actions environment
- Can be restricted to specific branches/paths

## 🚀 **Deployment Process**

1. **Add workflow file** to private repository
2. **Configure repository permissions** for Actions
3. **Test with sample PR** to validate functionality
4. **Customize rules** in local .cursorrules if needed
5. **Train team** on compliance requirements

## 📊 **Monitoring & Maintenance**

- **Action logs** available in GitHub Actions tab
- **Usage tracking** in repository Insights
- **Rule updates** via cursor_rules repository changes
- **Custom metrics** via workflow reporting

---

**Decision needed**: Should we proceed with Option 1 (Self-hosted per repo) for maximum flexibility and private repo compatibility?
